// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Dish struct {
	ID              pgtype.UUID      `db:"id" json:"id"`
	Name            string           `db:"name" json:"name"`
	Description     pgtype.Text      `db:"description" json:"description"`
	Price           pgtype.Numeric   `db:"price" json:"price"`
	PrepTimeMinutes int32            `db:"prep_time_minutes" json:"prep_time_minutes"`
	AvailableOn     pgtype.Date      `db:"available_on" json:"available_on"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Notification struct {
	ID      pgtype.UUID      `db:"id" json:"id"`
	UserID  pgtype.UUID      `db:"user_id" json:"user_id"`
	OrderID pgtype.UUID      `db:"order_id" json:"order_id"`
	Message string           `db:"message" json:"message"`
	SentAt  pgtype.Timestamp `db:"sent_at" json:"sent_at"`
}

type Order struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	UserID    pgtype.UUID      `db:"user_id" json:"user_id"`
	DishID    pgtype.UUID      `db:"dish_id" json:"dish_id"`
	Status    string           `db:"status" json:"status"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Permission struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
}

type Role struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
}

type RolePermission struct {
	RoleID       pgtype.UUID `db:"role_id" json:"role_id"`
	PermissionID pgtype.UUID `db:"permission_id" json:"permission_id"`
}

type User struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	Name      string           `db:"name" json:"name"`
	Email     string           `db:"email" json:"email"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type UserRole struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	RoleID pgtype.UUID `db:"role_id" json:"role_id"`
}
