// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateDish(ctx context.Context, arg CreateDishParams) (Dish, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDish(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetDish(ctx context.Context, id pgtype.UUID) (Dish, error)
	GetDishByName(ctx context.Context, name string) (Dish, error)
	GetDishesByDate(ctx context.Context, availableOn pgtype.Date) ([]Dish, error)
	GetNotificationsByUserId(ctx context.Context, userID pgtype.UUID) ([]Notification, error)
	GetOrder(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrdersByDishId(ctx context.Context, dishID pgtype.UUID) ([]Order, error)
	GetOrdersByStatus(ctx context.Context, status string) ([]Order, error)
	GetOrdersByUserId(ctx context.Context, userID pgtype.UUID) ([]GetOrdersByUserIdRow, error)
	GetPermissions(ctx context.Context) ([]Permission, error)
	GetRolePermissions(ctx context.Context) ([]RolePermission, error)
	GetRoles(ctx context.Context) ([]Role, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserRoles(ctx context.Context) ([]UserRole, error)
	ListDishes(ctx context.Context) ([]Dish, error)
	UpdateDish(ctx context.Context, arg UpdateDishParams) (Dish, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
